#ifndef OBJOMF_H_INCLUDED
#define OBJOMF_H_INCLUDED

#include <stdint.h>

#define readindex(x) ((readbyte(x) << 8) & 0x7F) + readbyte(x + 1)

enum omf_record_types {
    OMF_REC32 = 0x01, // 32bit records flag
    OMF_THEADR = 0x80,
    OMF_COMENT = 0x88,
    OMF_MODEND16 = 0x8A,
    OMF_MODEND32 = 0x8B,
    OMF_EXTDEF = 0x8C,
    OMF_TYPDEF = 0x8E,
    OMF_PUBDEF16 = 0x90,
    OMF_PUBDEF32 = 0x91,
    OMF_LINENUM16 = 0x94,
    OMF_LINENUM32 = 0x95,
    OMF_LNAMES = 0x96,
    OMF_SEGDEF16 = 0x98,
    OMF_SEGDEF32 = 0x99,
    OMF_GRPDEF = 0x9A,
    OMF_FIXUP16 = 0x9C,
    OMF_FIXUP32 = 0x9D,
    OMF_LEDATA16 = 0xA0,
    OMF_LEDATA32 = 0xA1,
    OMF_LIDATA16 = 0xA2,
    OMF_LIDATA32 = 0xA3,
    OMF_COMDEF = 0xB0,
    OMF_BAKPAT16 = 0xB2,
    OMF_BAKPAT32 = 0xB3,
    OMF_LEXTDEF16 = 0xB4,
    OMF_LEXTDEF32 = 0xB5,
    OMF_LPUBDEF16 = 0xB6,
    OMF_LPUBDEF32 = 0xB7,
    OMF_LCOMDEF = 0xB8,
    OMF_CEXTDEF = 0xBC,
    OMF_COMDAT16 = 0xC2,
    OMF_COMDAT32 = 0xC3,
    OMF_LINSYM16 = 0xC4,
    OMF_LINSYM32 = 0xC5,
    OMF_ALIAS = 0xC6,
    OMF_NBKPAT16 = 0xC8,
    OMF_NBKPAT32 = 0xC9,
    OMF_LLNAMES = 0xCA,
    OMF_VERNUM = 0xCC,
    OMF_VENDEXT = 0xCE,
    OMF_LIBRARY = 0xF0,
    OMF_LIBEND = 0xF1,
};

enum omf_coment_record_types {
    OMF_COMENT_TYPE_NO_LIST = 0x40,
    OMF_COMENT_TYPE_NO_PURGE = 0x80,
};

enum omf_coment_records_classes {
    OMF_COMENT_CLASS_TRANSLATOR = 0x00,
    OMF_COMENT_CLASS_INTEL_COPYRIGHT = 0x01,
    OMF_COMENT_CLASS_LIBRARY_IDENTIFIER = 0x81,
    OMF_COMENT_CLASS_DEPENDENCY_FILE = 0x88,
    OMF_COMENT_CLASS_MS_DOS_VERSION = 0x9C,
    OMF_COMENT_CLASS_MEMORY_MODEL = 0x9D,
    OMF_COMENT_CLASS_DOSSEG = 0x9E,
    OMF_COMENT_CLASS_DEFAULT_LIB_SEARCH_NAME = 0x9F,
    OMF_COMENT_CLASS_OMF_EXT = 0xA0,
    OMF_COMENT_CLASS_NEW_OMF_EXT = 0xA1,
    OMF_COMENT_CLASS_LINK_PASS_SEPERATOR = 0xA2,
    OMF_COMENT_CLASS_LIBMOD = 0xA3,
    OMF_COMENT_CLASS_EXESTR = 0xA4,
    OMF_COMENT_CLASS_INCERR = 0xA6,
    OMF_COMENT_CLASS_NOPAD = 0xA7,
    OMF_COMENT_CLASS_WKEXT = 0xA8,
    OMF_COMENT_CLASS_LZEXT = 0xA9,
    OMF_COMENT_CLASS_BORLAND_TYPES = 0xE3,
    OMF_COMENT_CLASS_BORLAND_SYMBOLS = 0xE6,
    OMF_COMENT_CLASS_BORLAND_SOURCE = 0xE8,
    OMF_COMENT_CLASS_BORLAND_DEPENDENCY_FILES = 0xE9,
    OMF_COMENT_CLASS_COMMENT = 0xDA,
    OMF_COMENT_CLASS_COMPILER = 0xDB,
    OMF_COMENT_CLASS_DATE = 0xDC,
    OMF_COMENT_CLASS_TIMESTAMP = 0xDD,
    OMF_COMENT_CLASS_USER = 0xDE,
    OMF_COMENT_CLASS_COMMAND_LINE = 0xFF,
};

#pragma pack(1)

struct omf_record_header {
    uint8_t record_type;
    uint16_t record_size;
};

#pragma pack()

#endif